---
title: "exploration"
author: "Yiming Chen"
date: "2025-09-05"
output: html_document
---
try simple structure first (one loading for each item) for five factors
use sim30GDINA for five factors

number of factors
structure of Q matrix (a)
might affect correlation
```{r}
library(GDINA)
library(mirt)
```

```{r}
Q <- GDINA::sim30GDINA$simQ
Q
```

```{r}
# discrimination parameter
a <- 1.5 * Q
a[a == 0] <- NA
a <- as.matrix(a)
a
```

```{r}
# constant number
d <- matrix(rep(0, 30), ncol = 1)
```

```{r}
theta <- matrix(rnorm(2000 * 5), ncol = 5)
dim(theta)
head(theta)
```

```{r}
data1 <- simdata(a, d, 2000, itemtype = '2PL', Theta = theta)
dim(data1)
head(data1)
```

```{r}
est <- GDINA(data1, Q)
mp <- personparm(est, "mp")
```

```{r}
cor(theta[,2], mp[,2])
```

# 5 dimension/factors
```{r}
r <- matrix(0.5,5,5)
#r <- matrix(0,5,5)
#r <- matrix(0.3,5,5)
#r <- matrix(0.6,5,5)
diag(r) <- 1
r

Theta <- mvtnorm::rmvnorm(2000,sigma=r)
head(Theta)
```

```{r}
a <- matrix(NA, nrow=18, ncol=5)
a[1:10,1] <- runif(10, 0.5, 2)
a[7:13,2] <- runif(7, 0.5, 2)
a[11:15,3] <- runif(5, 0.5, 2)
a[10:18,4] <- runif(9, 0.5, 2)
a[c(1, 3, 6, 10, 17, 18), 5] <- runif(6, 0.5, 2)
head(a)
dim(a)
#lognorm 0 & 1
```

```{r}
d <- matrix(rnorm(nrow(a)))
d
itemtype <- rep('2PL',nrow(a))
```

```{r}
simmirt <- simdata(a=a, d=d, itemtype=itemtype, Theta=Theta)
head(simmirt)
```

```{r}
model <- '
F1 = 1-9
F2 = 7-10
F3 = 10-13
F4 = 13-15
F5 = 15-18
COV=F1*F2*F3*F4*F5
'

mod <- mirt(simmirt, model, 
            method = "QMCEM", # "MHRM"
            quadpts = 500)
coef(mod)
```

```{r}
Q=(!is.na(a))*1
est=GDINA(simmirt,Q)

x1=personparm(est,"mp") # mastery probability for each attribute
head(x1)

x2=fscores(mod, QMC = TRUE) # theta for each dimension from mirt
head(x2)
```

```{r}
plot(qnorm(x1[,1]),x2[,1])
#cor(x1[,2], pnorm(x2[,2]))
#cor(x1[,1], pnorm(x2[,1]))

cor(qnorm(x1[,1]), x2[,1])
cor(qnorm(x1[,2]), x2[,2])
cor(qnorm(x1[,3]), x2[,3])
cor(qnorm(x1[,4]), x2[,4])
cor(qnorm(x1[,5]), x2[,5])

# spearman correlation
cor(qnorm(x1[,1]), x2[,1], method = "spearman")
cor(qnorm(x1[,2]), x2[,2], method = "spearman")
cor(qnorm(x1[,3]), x2[,3], method = "spearman")
cor(qnorm(x1[,4]), x2[,4], method = "spearman")
cor(qnorm(x1[,5]), x2[,5], method = "spearman")
```
















